version: '3'

services:
  telegram-bot:
    build: .
    container_name: pho-telegram-bot
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./users.json:/var/www/html/users.json
      - ./error.log:/var/www/html/error.log
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1m
      timeout: 10s
      retries: 3